import {addeZero} from './trail-zero';
import  moment from 'moment';

export const getEvets = (sunday, monday, tueseday, wednesday, thursday, friday, saturday) => {
  // get data for all week day.(SchedulerEvent0StartType,SchedulerEvent1StartType,SchedulerEvent0StartType,...)
  const events = [
    {
      id: sunday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent0StartHour.Value)}:${addeZero(sunday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent0EndHour.Value)}:${addeZero(sunday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: sunday.SchedulerEvent0StartHour.Value,
      endTime: sunday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
      color: sunday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: sunday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent1StartHour.Value)}:${addeZero(sunday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent1EndHour.Value)}:${addeZero(sunday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: sunday.SchedulerEvent1StartHour.Value,
      endTime: sunday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
      color: sunday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'

    },
    {
      id: sunday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent2StartHour.Value)}:${addeZero(sunday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent2EndHour.Value)}:${addeZero(sunday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: sunday.SchedulerEvent2StartHour.Value,
      endTime: sunday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
      color: sunday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: sunday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent3StartHour.Value)}:${addeZero(sunday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent3EndHour.Value)}:${addeZero(sunday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: sunday.SchedulerEvent3StartHour.Value,
      endTime: sunday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
      color: sunday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: sunday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent4StartHour.Value)}:${addeZero(sunday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent4EndHour.Value)}:${addeZero(sunday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: sunday.SchedulerEvent4StartHour.Value,
      endTime: sunday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
      color: sunday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: sunday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent5StartHour.Value)}:${addeZero(sunday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-21T${addeZero(sunday.SchedulerEvent5EndHour.Value)}:${addeZero(sunday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: sunday.SchedulerEvent5StartHour.Value,
      endTime: sunday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
      color: sunday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },    
    {
      id: monday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent0StartHour.Value)}:${addeZero(monday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent0EndHour.Value)}:${addeZero(monday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: monday.SchedulerEvent0StartHour.Value,
      endTime: monday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: monday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: monday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent1StartHour.Value)}:${addeZero(monday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent1EndHour.Value)}:${addeZero(monday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: monday.SchedulerEvent1StartHour.Value,
      endTime: monday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: monday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: monday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent2StartHour.Value)}:${addeZero(monday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent2EndHour.Value)}:${addeZero(monday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: monday.SchedulerEvent2StartHour.Value,
      endTime: monday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: monday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: monday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent3StartHour.Value)}:${addeZero(monday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent3EndHour.Value)}:${addeZero(monday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: monday.SchedulerEvent3StartHour.Value,
      endTime: monday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: monday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: monday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent4StartHour.Value)}:${addeZero(monday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent4EndHour.Value)}:${addeZero(monday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: monday.SchedulerEvent4StartHour.Value,
      endTime: monday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: monday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: monday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-22T${addeZero(monday.SchedulerEvent5StartHour.Value)}:${addeZero(monday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-22T${addeZero(monday.SchedulerEvent5EndHour.Value)}:${addeZero(monday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: monday.SchedulerEvent5StartHour.Value,
      endTime: monday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: monday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent0StartHour.Value)}:${addeZero(tueseday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent0EndHour.Value)}:${addeZero(tueseday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: tueseday.SchedulerEvent0StartHour.Value,
      endTime: tueseday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: tueseday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent1StartHour.Value)}:${addeZero(tueseday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent1EndHour.Value)}:${addeZero(tueseday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: tueseday.SchedulerEvent1StartHour.Value,
      endTime: tueseday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: tueseday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent2StartHour.Value)}:${addeZero(tueseday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent2EndHour.Value)}:${addeZero(tueseday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: tueseday.SchedulerEvent2StartHour.Value,
      endTime: tueseday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: tueseday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent3StartHour.Value)}:${addeZero(tueseday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent3EndHour.Value)}:${addeZero(tueseday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: tueseday.SchedulerEvent3StartHour.Value,
      endTime: tueseday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: tueseday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent4StartHour.Value)}:${addeZero(tueseday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent4EndHour.Value)}:${addeZero(tueseday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: tueseday.SchedulerEvent4StartHour.Value,
      endTime: tueseday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: tueseday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: tueseday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent5StartHour.Value)}:${addeZero(tueseday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-23T${addeZero(tueseday.SchedulerEvent5EndHour.Value)}:${addeZero(tueseday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: tueseday.SchedulerEvent5StartHour.Value,
      endTime: tueseday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: tueseday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent0StartHour.Value)}:${addeZero(wednesday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent0EndHour.Value)}:${addeZero(wednesday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: wednesday.SchedulerEvent0StartHour.Value,
      endTime: wednesday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: wednesday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent1StartHour.Value)}:${addeZero(wednesday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent1EndHour.Value)}:${addeZero(wednesday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: wednesday.SchedulerEvent1StartHour.Value,
      endTime: wednesday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: wednesday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent2StartHour.Value)}:${addeZero(wednesday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent2EndHour.Value)}:${addeZero(wednesday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: wednesday.SchedulerEvent2StartHour.Value,
      endTime: wednesday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: wednesday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent3StartHour.Value)}:${addeZero(wednesday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent3EndHour.Value)}:${addeZero(wednesday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: wednesday.SchedulerEvent3StartHour.Value,
      endTime: wednesday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: wednesday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent4StartHour.Value)}:${addeZero(wednesday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent4EndHour.Value)}:${addeZero(wednesday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: wednesday.SchedulerEvent4StartHour.Value,
      endTime: wednesday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: wednesday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: wednesday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent5StartHour.Value)}:${addeZero(wednesday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-24T${addeZero(wednesday.SchedulerEvent5EndHour.Value)}:${addeZero(wednesday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: wednesday.SchedulerEvent5StartHour.Value,
      endTime: wednesday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: wednesday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent0StartHour.Value)}:${addeZero(thursday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent0EndHour.Value)}:${addeZero(thursday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: thursday.SchedulerEvent0StartHour.Value,
      endTime: thursday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: thursday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent1StartHour.Value)}:${addeZero(thursday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent1EndHour.Value)}:${addeZero(thursday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: thursday.SchedulerEvent1StartHour.Value,
      endTime: thursday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: thursday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent2StartHour.Value)}:${addeZero(thursday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent2EndHour.Value)}:${addeZero(thursday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: thursday.SchedulerEvent2StartHour.Value,
      endTime: thursday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: thursday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent3StartHour.Value)}:${addeZero(thursday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent3EndHour.Value)}:${addeZero(thursday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: thursday.SchedulerEvent3StartHour.Value,
      endTime: thursday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: thursday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent4StartHour.Value)}:${addeZero(thursday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent4EndHour.Value)}:${addeZero(thursday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: thursday.SchedulerEvent4StartHour.Value,
      endTime: thursday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: thursday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: thursday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent5StartHour.Value)}:${addeZero(thursday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-25T${addeZero(thursday.SchedulerEvent5EndHour.Value)}:${addeZero(thursday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: thursday.SchedulerEvent5StartHour.Value,
      endTime: thursday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: thursday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent0StartHour.Value)}:${addeZero(friday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent0EndHour.Value)}:${addeZero(friday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: friday.SchedulerEvent0StartHour.Value,
      endTime: friday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: friday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent1StartHour.Value)}:${addeZero(friday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent1EndHour.Value)}:${addeZero(friday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: friday.SchedulerEvent1StartHour.Value,
      endTime: friday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: friday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent2StartHour.Value)}:${addeZero(friday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent2EndHour.Value)}:${addeZero(friday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: friday.SchedulerEvent2StartHour.Value,
      endTime: friday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: friday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent3StartHour.Value)}:${addeZero(friday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent3EndHour.Value)}:${addeZero(friday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3tartType',
      startTime: friday.SchedulerEvent3StartHour.Value,
      endTime: friday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: friday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent4StartHour.Value)}:${addeZero(friday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent4EndHour.Value)}:${addeZero(friday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: friday.SchedulerEvent4StartHour.Value,
      endTime: friday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: friday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: friday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-26T${addeZero(friday.SchedulerEvent5StartHour.Value)}:${addeZero(friday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-26T${addeZero(friday.SchedulerEvent5EndHour.Value)}:${addeZero(friday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: friday.SchedulerEvent5StartHour.Value,
      endTime: friday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: friday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent0StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent0StartHour.Value)}:${addeZero(saturday.SchedulerEvent0StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent0EndHour.Value)}:${addeZero(saturday.SchedulerEvent0EndMinute.Value)}:00`),
      startH: 'SchedulerEvent0StartHour',
      endH: 'SchedulerEvent0EndHour',
      startM: 'SchedulerEvent0StartMinute',
      endM: 'SchedulerEvent0EndMinute',
      startType: 'SchedulerEvent0StartType',
      startTime: saturday.SchedulerEvent0StartHour.Value,
      endTime: saturday.SchedulerEvent0EndHour.Value,
      eventNumber: 0,
      endType:'SchedulerEvent0EndType',
          color: saturday.SchedulerEvent0StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent1StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent1StartHour.Value)}:${addeZero(saturday.SchedulerEvent1StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent1EndHour.Value)}:${addeZero(saturday.SchedulerEvent1EndMinute.Value)}:00`),
      startH: 'SchedulerEvent1StartHour',
      endH: 'SchedulerEvent1EndHour',
      startM: 'SchedulerEvent1StartMinute',
      endM: 'SchedulerEvent1EndMinute',
      startType: 'SchedulerEvent1StartType',
      startTime: saturday.SchedulerEvent1StartHour.Value,
      endTime: saturday.SchedulerEvent1EndHour.Value,
      eventNumber: 1,
      endType:'SchedulerEvent1EndType',
          color: saturday.SchedulerEvent1StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent2StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent2StartHour.Value)}:${addeZero(saturday.SchedulerEvent2StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent2EndHour.Value)}:${addeZero(saturday.SchedulerEvent2EndMinute.Value)}:00`),
      startH: 'SchedulerEvent2StartHour',
      endH: 'SchedulerEvent2EndHour',
      startM: 'SchedulerEvent2StartMinute',
      endM: 'SchedulerEvent2EndMinute',
      startType: 'SchedulerEvent2StartType',
      startTime: saturday.SchedulerEvent2StartHour.Value,
      endTime: saturday.SchedulerEvent2EndHour.Value,
      eventNumber: 2,
      endType:'SchedulerEvent2EndType',
          color: saturday.SchedulerEvent2StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent3StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent3StartHour.Value)}:${addeZero(saturday.SchedulerEvent3StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent3EndHour.Value)}:${addeZero(saturday.SchedulerEvent3EndMinute.Value)}:00`),
      startH: 'SchedulerEvent3StartHour',
      endH: 'SchedulerEvent3EndHour',
      startM: 'SchedulerEvent3StartMinute',
      endM: 'SchedulerEvent3EndMinute',
      startType: 'SchedulerEvent3StartType',
      startTime: saturday.SchedulerEvent3StartHour.Value,
      endTime: saturday.SchedulerEvent3EndHour.Value,
      eventNumber: 3,
      endType:'SchedulerEvent3EndType',
          color: saturday.SchedulerEvent3StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent4StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent4StartHour.Value)}:${addeZero(saturday.SchedulerEvent4StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent4EndHour.Value)}:${addeZero(saturday.SchedulerEvent4EndMinute.Value)}:00`),
      startH: 'SchedulerEvent4StartHour',
      endH: 'SchedulerEvent4EndHour',
      startM: 'SchedulerEvent4StartMinute',
      endM: 'SchedulerEvent4EndMinute',
      startType: 'SchedulerEvent4StartType',
      startTime: saturday.SchedulerEvent4StartHour.Value,
      endTime: saturday.SchedulerEvent4EndHour.Value,
      eventNumber: 4,
      endType:'SchedulerEvent4EndType',
          color: saturday.SchedulerEvent4StartType.Value==='3'?'#0271BE':'#05940A'
    },
    {
      id: saturday.SchedulerEvent5StartType.Value,
      title: '',
      start: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent5StartHour.Value)}:${addeZero(saturday.SchedulerEvent5StartMinute.Value)}:00`),
      end: moment(`2018-10-27T${addeZero(saturday.SchedulerEvent5EndHour.Value)}:${addeZero(saturday.SchedulerEvent5EndMinute.Value)}:00`),
      startH: 'SchedulerEvent5StartHour',
      endH: 'SchedulerEvent5EndHour',
      startM: 'SchedulerEvent5StartMinute',
      endM: 'SchedulerEvent5EndMinute',
      startType: 'SchedulerEvent5StartType',
      startTime: saturday.SchedulerEvent5StartHour.Value,
      endTime: saturday.SchedulerEvent5EndHour.Value,
      eventNumber: 5,
      endType:'SchedulerEvent5EndType',
          color: saturday.SchedulerEvent5StartType.Value==='3'?'#0271BE':'#05940A'
    },
  ];
  
  return events;
}


export const getEventsShift=(sunday, monday, tueseday, wednesday, thursday, friday, saturday)=>{
  const events=[]
  for(let day=0;day<7; day++){
    let dates=["2018-10-21T","2018-10-22T","2018-10-23T","2018-10-24T","2018-10-25T","2018-10-26T","2018-10-27T"]
    let weeks=[sunday, monday, tueseday, wednesday, thursday, friday, saturday] 
    //for getting all the events time 
    let strtHr=(i)=>`ShiftEvent${i}StartHour`  
    let endHr=(i)=>`ShiftEvent${i}EndHour`
    let startMin=(i)=>`ShiftEvent${i}StartMinute`
    let endMin=(i)=>`ShiftEvent${i}EndMinute`
    
    for(let event=0; event<5; event++){
          let colrs=['#c6cbf5','#EDA1F7','#9B78F7','#7543F4','#5527C8']
          let eventShift=new shiftEvent(
                                  dates[day],
                                  weeks[day][strtHr(event)].Value,
                                  weeks[day][endHr(event)].Value,
                                  weeks[day][startMin(event)].Value,
                                  weeks[day][endMin(event)].Value,
                                  event,
                                  colrs[event])
           events.push(eventShift)
         }
    }
    return events;
  }


class shiftEvent{
  start;end; startH;endH;startM; endM;color;shift;id;
  constructor(date,startHour,endHour,startMinute,EndMinute,shiftLevel,color){
   
    this.start=moment(`${date}${addeZero(startHour)}:${addeZero(startMinute)}:00`);
    this.end= moment(`${date}${addeZero(endHour)}:${addeZero(EndMinute)}:00`);
    this.startH=startHour;
    this.endH=endHour;
    this.startM=startMinute;
    this.endM=EndMinute;
    this.color=color;
    this.shift=shiftLevel
  }
  
}