export const environment = {
  production: true,
   BASE_URI: 'http://13.90.243.43:3200/api',
  //BASE_URI:'https://bbconncloudapi.nordson.com/api',
  // BASE_URI:'http://omubestaging.eastus.cloudapp.azure.com/api',
  validate:'emailvalidate',
  userdetails:'userDetails',
  subUser:'subuser',
  accessories:"/recipe/accessmanage",
  heatScheduler:"/recipe/heatschedule",
  shiftScheduler:"/recipe/shiftschedule",
  sysSecurity:"/getsystemsecurity",
  recipeList:"/recipelist",
  createRecipe:"/norfile/create",
  importNorFile:"/norfile/upload",
  openRecipe:"/openrecipe",
  renameRecipe:"/renamerecipe",
  exportRecipe:"/exportrecipe",
  updatePressure:"/updatepressure",
  updateTempzone:"/updatetempzone",
  createNewRecipe:"/recipecreate",
  defaultRecipeData:"/defaultrecipeval",
  eventLogEventFilter:"/eventlogs/byeventtypes/",
  eventLogZoneFilter:"/eventlogs/byzones/",
  eventLogAllZones:"/eventlogs/zones",
  eventLogDateFilter:"/eventlogs/bydate",//bydatelogcounts
  eventLogAllFilters:"/eventlogs/eventypesandzones",
  importxmlFile: "/import-recipe",
  tempConvert: "/tempconvert",
  pressureConvert: "/pressureconvert",
  contactUs: "/contact-us",
  editDescription: "/edit-description",
  lineSpeedConvert:'/line-speed-convert',
  deleteRecipe: "/remove-recipe-file"
};
